version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    # en mode net=host, on désactive les ports
    #ports:
    #  - "53:53/tcp"
    #  - "53:53/udp"
    #  - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
    #  - "80:80/tcp"
    environment:
      TZ: 'Europe/Paris'
      WEBPASSWORD: 'admin'
      DHCP_ACTIVE: 'true'
      DHCP_START: 192.168.1.150
      DHCP_END: 192.168.1.200
      DHCP_ROUTER: 192.168.1.250
      # If you're trying to use DHCP with --net host mode then you may have to customize this or DNSMASQ_LISTENING (https://hub.docker.com/r/pihole/pihole). 
      INTERFACE: wlan0
      
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'    
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN)      
    restart: unless-stopped
